#./SKMCplots "/home/dm3315/Documents/T2K-SK/NCpi0/figs/selection_plots/" "fhc" "1ringPID" 
#./SKMCplots "/home/dm3315/Documents/T2K-SK/NCpi0/figs/selection_plots/" "fhc" "noemuPID_" 
./SKMCfomPlots "/home/dm3315/Documents/T2K-SK/NCpi0/figs/selection_plots/tuned/" "NCpi0_MC_histos_tuned_t2ksk19b.fqv4r0.fhc.all.root" 
#./SKMCplots "/home/dm3315/Documents/T2K-SK/NCpi0/figs/selection_plots/" "fhc" "2ReePID" 
#./SKMCplots "/home/dm3315/Documents/T2K-SK/NCpi0/figs/selection_plots/" "fhc" "" 
#./SKMCplots "/home/dm3315/Documents/T2K-SK/NCpi0/figs/selection_plots/" "rhc" "1ringPID" 
#./SKMCplots "/home/dm3315/Documents/T2K-SK/NCpi0/figs/selection_plots/" "rhc" "noemuPID_" 
#./SKMCplots "/home/dm3315/Documents/T2K-SK/NCpi0/figs/selection_plots/" "rhc" "2ringPID" 
#./SKMCplots "/home/dm3315/Documents/T2K-SK/NCpi0/figs/selection_plots/" "rhc" "2ReePID" 
#./SKMCplots "/home/dm3315/Documents/T2K-SK/NCpi0/figs/selection_plots/" "rhc" "" 
